autoVerticalizationAreaRatio: 0.01
borderPointsAutoFilterPixelOffset: 5
closenessAreaRatio: 0.002
contourCornerPointsCheckTresh: 0.1
contourRemovalThreshold: 77
darkSegmentThresh: 0.76
deviationFactor: 4
enteranceThresh: 0.3
highH: 7
highS: 77
highV: 188
horizontalKernelSize: 15
hugeContourAreaRatioFilter: 0.8
lowARRatioAutoFilter: 0.3
lowAreaRatioAutoFilter: 0.1
lowContourAreaFilter: 100
lowContourLenFilter: 3
lowH: 0
lowS: 58
lowV: 76
peakNeighbourhood: 40
segmentExtractionPixelOffset: 10
segmentThreshold: 0.02
segmentationMethod: 1
thresh: 12
trackerCorrectionPixelOffset: 10
trackerInitPixelOffset: 10
upARRatioAutoFilter: 2
upAreaRatioAutoFilter: 3.5
verticalCenter: 0.25
verticalKernelSize: 10
windowHeight: 2
windowWidth: 1.4
